version: "3.8"

services:
  node-exporter:
    container_name: grafana-node-exporter
    image: prom/node-exporter
    # ports:
    #   - "9100:9100"
    networks:
      - grafana_network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped

  prometheus:
    container_name: grafana-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - grafana_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  grafana_storage: {}

networks:
  grafana_network:
    driver: bridge
