global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['grafana-prometheus:9090']
        labels:
          instance: prometheus

  - job_name: localhost
    static_configs:
      - targets: ['grafana-node-exporter:9100']
        labels:
          instance: localhost