version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    # user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "navidrome_storage:/data"
      - "music:/music:ro"

volumes:
  navidrome_storage: {}
  music:
    driver: rclone
    driver_opts:
      remote: 'od:Music'
      allow_other: 'true'
      vfs_cache_mode: writes
      poll_interval: 0
