version: "3.3"

services:
  nezha-agent:
    image: kuusei/nezha-agent:latest
    restart: always
    container_name: nezha-agent
    environment:
      - domain=${DASHBOARD_DOMAIN}
      - port=5555
      - secret=${SECRET}
      - args=--disable-auto-update --disable-command-execute
    network_mode: host